package com.example.ticketentregaapp.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors - Modern Blue Palette
val md_theme_light_primary = Color(0xFF1976D2)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD3E4FD)
val md_theme_light_onPrimaryContainer = Color(0xFF001B3D)
val md_theme_light_secondary = Color(0xFF4A5F7F)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFDBE7FF)
val md_theme_light_onSecondaryContainer = Color(0xFF051B37)
val md_theme_light_tertiary = Color(0xFF6750A4)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE9DDFF)
val md_theme_light_onTertiaryContainer = Color(0xFF22005D)
val md_theme_light_error = Color(0xFFD32F2F)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFAFBFF)
val md_theme_light_onBackground = Color(0xFF191C20)
val md_theme_light_surface = Color(0xFFFAFBFF)
val md_theme_light_onSurface = Color(0xFF191C20)
val md_theme_light_surfaceVariant = Color(0xFFE0E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF43474E)
val md_theme_light_outline = Color(0xFF74777F)
val md_theme_light_inverseOnSurface = Color(0xFFF0F0F7)
val md_theme_light_inverseSurface = Color(0xFF2E3036)
val md_theme_light_inversePrimary = Color(0xFFA8C7FA)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF1976D2)
val md_theme_light_outlineVariant = Color(0xFFC4C6D0)
val md_theme_light_scrim = Color(0xFF000000)

// Dark Theme Colors - Modern Dark Blue Palette
val md_theme_dark_primary = Color(0xFFA8C7FA)
val md_theme_dark_onPrimary = Color(0xFF003062)
val md_theme_dark_onPrimaryContainer = Color(0xFFD3E4FD)
val md_theme_dark_primaryContainer = Color(0xFF004B8D)
val md_theme_dark_secondary = Color(0xFFB8C8E8)
val md_theme_dark_onSecondary = Color(0xFF1C314D)
val md_theme_dark_secondaryContainer = Color(0xFF334864)
val md_theme_dark_onSecondaryContainer = Color(0xFFDBE7FF)
val md_theme_dark_tertiary = Color(0xFFCFBCFF)
val md_theme_dark_onTertiary = Color(0xFF381E72)
val md_theme_dark_tertiaryContainer = Color(0xFF4F378A)
val md_theme_dark_onTertiaryContainer = Color(0xFFE9DDFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C20)
val md_theme_dark_onBackground = Color(0xFFE1E2E8)
val md_theme_dark_surface = Color(0xFF191C20)
val md_theme_dark_onSurface = Color(0xFFE1E2E8)
val md_theme_dark_surfaceVariant = Color(0xFF43474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C6D0)
val md_theme_dark_outline = Color(0xFF8D9199)
val md_theme_dark_inverseOnSurface = Color(0xFF191C20)
val md_theme_dark_inverseSurface = Color(0xFFE1E2E8)
val md_theme_dark_inversePrimary = Color(0xFF1976D2)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFA8C7FA)
val md_theme_dark_outlineVariant = Color(0xFF43474E)
val md_theme_dark_scrim = Color(0xFF000000)

// Custom Accent Colors
val SuccessGreen = Color(0xFF4CAF50)
val WarningOrange = Color(0xFFFB8C00)
val InfoBlue = Color(0xFF2196F3)